version: '3.9'

services:

  postgres:
      container_name: postgres-aws-demo
      hostname: postgres
      image: postgres:14.1-alpine
      ports: 
        - "5432:5432"
      environment:
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: postgres

  localstack:
    container_name: localstack
    image: localstack/localstack:latest
    environment:
      - AWS_DEFAULT_REGION=us-east-1
      - EDGE_PORT=4566
      - SERVICES=lambda,s3,kms
    ports:
      - "4566:4566" # The Edge port can multiplex all services
    volumes:
      - "${TEMPDIR:-/tmp/localstack}:/tmp/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
